### ISSUE TITLE
Choice of Auxiliar point

### ISSUE THREAD

**Issue by mishapadidar** [fontclos/hitandrun#4]
The argmax is over a boolean array, and so will always return the index of the first True element, i.e. the first nonzero element in the array. Whereas I think you wanted the largest nonzero element of the array.
https://github.com/fontclos/hitandrun/blob/2e6764deda7c600317c2c7e647b38933fd931e35/hitandrun/polytope.py#L51

I think you may have wanted
`j = np.argmax(Ai[Ai != 0])`

**Comment by fontclos** [comment]
I would say we actually want the first nonzero element in the array, any point is ok as long as it has Ai != 0. Why should we want the largest one?

**Comment by fontclos** [comment]
closing because inactive
